In [1]:
#! importing libraries

import pandas as pd
import numpy as np

In [2]:
# loading data

credits = pd.read_csv("../Data/raw/credits.csv")
movies_metadata = pd.read_csv("../Data/raw/movies_metadata.csv")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24532\965213456.py:4: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_metadata = pd.read_csv("../Data/raw/movies_metadata.csv")

In [3]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [4]:
movies_metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [5]:
# Convert release_date to datetime

movies_metadata["release_date"] = pd.to_datetime(movies_metadata["release_date"], errors="coerce") # Convert to datetime, error = "coerce" convert invalid dates to NaN

In [6]:
# format the date to year only

movies_metadata['year'] = movies_metadata['release_date'].dt.year

In [7]:
movies_metadata["year"].value_counts().sort_index()

year
1874.0       1
1878.0       1
1883.0       1
1887.0       1
1888.0       2
          ...
2015.0    1905
2016.0    1604
2017.0     532
2018.0       5
2020.0       1
Name: count, Length: 135, dtype: int64

In [8]:
# Getting only 2017 data as we already have movies data until 2016

movies_metadata_2017 = movies_metadata.loc[movies_metadata["year"] == 2017, ["id", "title", "year", "genres"]]

In [9]:
movies_metadata_2017

,id,title,year,genres
26560,166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '..."
26561,141052,Justice League,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
26565,284053,Thor: Ragnarok,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
26566,283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
30536,245842,The King's Daughter,2017.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na..."
...,...,...,...,...
45398,468707,Thick Lashes of Lauri Mäntyvaara,2017.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
45417,461297,Cop and a Half: New Recruit,2017.0,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name..."
45437,455661,In a Heartbeat,2017.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '..."
45453,404604,Mom,2017.0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name..."
45465,461257,Queerama,2017.0,[]

In [10]:
movies_metadata_2017.info()

<class 'pandas.DataFrame'>
Index: 532 entries, 26560 to 45465
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      532 non-null    str
 1   title   532 non-null    str
 2   year    532 non-null    float64
 3   genres  532 non-null    str
dtypes: float64(1), str(3)
memory usage: 20.8 KB

In [11]:
movies_metadata_2017["id"] = movies_metadata_2017["id"].astype(int)

In [12]:
df = pd.merge(movies_metadata_2017, credits, on="id")

In [13]:
df.head()

,id,title,year,genres,cast,crew
0,166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de..."
1,141052,Justice League,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de..."
2,284053,Thor: Ragnarok,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de..."
3,283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de..."
4,245842,The King's Daughter,2017.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...","[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de..."

In [14]:
import ast


df['genres'] = df['genres'].map(lambda x: ast.literal_eval(x))
df['cast'] = df['cast'].map(lambda x: ast.literal_eval(x))
df['crew'] = df['crew'].map(lambda x: ast.literal_eval(x))

In [15]:
df.head()

,id,title,year,genres,cast,crew
0,166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de..."
1,141052,Justice League,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de..."
2,284053,Thor: Ragnarok,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de..."
3,283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de..."
4,245842,The King's Daughter,2017.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...","[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de..."

In [16]:
def get_individual_genres(genres):
    gen = []
    st = ' '
    for i in genres:
        if i.get("name") == "Science Fiction":
            gen.append("Sci-Fi")
        else:
            gen.append(i.get("name"))
    
    if gen == []:
        return np.nan
    
    return st.join(gen)

In [17]:
df['genres_list'] = df['genres'].map(lambda x: get_individual_genres(x))

In [18]:
df['genres_list']

0      Adventure Action Fantasy Comedy
1      Action Adventure Fantasy Sci-Fi
2      Action Adventure Fantasy Sci-Fi
3       Action Adventure Comedy Sci-Fi
4             Fantasy Action Adventure
                    ...
526                     Romance Comedy
527         Crime Comedy Action Family
528    Family Animation Romance Comedy
529               Crime Drama Thriller
530                                NaN
Name: genres_list, Length: 531, dtype: str

In [19]:
def get_actor_1(cast):
    casts = []
    for i in cast:
        casts.append(i.get("name"))
    if casts == []:
        return np.nan
    else:
        return casts[0]

In [20]:
df['actor_1_name'] = df['cast'].map(lambda x: get_actor_1(x))

In [21]:
def get_actor_2(cast):
    casts = []
    for i in cast:
        casts.append(i.get("name"))
    if len(casts) < 2:
        return np.nan
    else:
        return casts[1]

In [22]:
df['actor_2_name'] = df['cast'].map(lambda x: get_actor_2(x))

In [23]:
def get_actor_3(cast):
    casts = []
    for i in cast:
        casts.append(i.get("name"))
    if len(casts) < 3:
        return np.nan
    else:
        return casts[2]

In [24]:
df['actor_3_name'] = df['cast'].map(lambda x: get_actor_3(x))

In [25]:
def get_director(crew):
    dt = []
    st = ' '
    for i in crew:
        if i.get("job") == "Director":
            dt.append(i.get("name"))
    if dt == []:
        return np.nan
    else:
        return st.join(dt)

In [26]:
df['director_name'] = df['crew'].map(lambda x: get_director(x))

In [27]:
df.head()

,id,title,year,genres,cast,crew,genres_list,actor_1_name,actor_2_name,actor_3_name,director_name
0,166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de...",Adventure Action Fantasy Comedy,Johnny Depp,Javier Bardem,Geoffrey Rush,Joachim Rønning Espen Sandberg
1,141052,Justice League,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de...",Action Adventure Fantasy Sci-Fi,Ben Affleck,Henry Cavill,Gal Gadot,Zack Snyder
2,284053,Thor: Ragnarok,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de...",Action Adventure Fantasy Sci-Fi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Taika Waititi
3,283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",Action Adventure Comedy Sci-Fi,Chris Pratt,Zoe Saldana,Dave Bautista,James Gunn
4,245842,The King's Daughter,2017.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...","[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de...",Fantasy Action Adventure,Pierce Brosnan,William Hurt,Benjamin Walker,Sean McNamara

In [28]:
# Selecting the same columns as per the previous dataset

df = df.loc[:, ["director_name", "actor_1_name", "actor_2_name", "actor_3_name", "genres_list", "title"]]
df.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres_list,title
0,Joachim Rønning Espen Sandberg,Johnny Depp,Javier Bardem,Geoffrey Rush,Adventure Action Fantasy Comedy,Pirates of the Caribbean: Dead Men Tell No Tales
1,Zack Snyder,Ben Affleck,Henry Cavill,Gal Gadot,Action Adventure Fantasy Sci-Fi,Justice League
2,Taika Waititi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Action Adventure Fantasy Sci-Fi,Thor: Ragnarok
3,James Gunn,Chris Pratt,Zoe Saldana,Dave Bautista,Action Adventure Comedy Sci-Fi,Guardians of the Galaxy Vol. 2
4,Sean McNamara,Pierce Brosnan,William Hurt,Benjamin Walker,Fantasy Action Adventure,The King's Daughter

In [29]:
df.isna().sum()

director_name     4
actor_1_name     22
actor_2_name     55
actor_3_name     70
genres_list       7
title             0
dtype: int64

In [30]:
df.shape

(531, 6)

In [31]:
df.dropna(how="any", inplace=True)

In [32]:
df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres_list      0
title            0
dtype: int64

In [33]:
df.shape

(458, 6)

In [34]:
df = df.rename(columns={"title": "movie_title"})
df = df.rename(columns={"genres_list": "genres"})

In [35]:
df['movie_title'] = df['movie_title'].str.lower()

In [36]:
df['comb'] = df['actor_1_name'] + ' ' + df['actor_2_name'] + ' ' + df['actor_3_name'] + ' ' + df['director_name'] + ' ' + df['genres']

In [37]:
df.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Joachim Rønning Espen Sandberg,Johnny Depp,Javier Bardem,Geoffrey Rush,Adventure Action Fantasy Comedy,pirates of the caribbean: dead men tell no tales,Johnny Depp Javier Bardem Geoffrey Rush Joachi...
1,Zack Snyder,Ben Affleck,Henry Cavill,Gal Gadot,Action Adventure Fantasy Sci-Fi,justice league,Ben Affleck Henry Cavill Gal Gadot Zack Snyder...
2,Taika Waititi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Action Adventure Fantasy Sci-Fi,thor: ragnarok,Chris Hemsworth Tom Hiddleston Cate Blanchett ...
3,James Gunn,Chris Pratt,Zoe Saldana,Dave Bautista,Action Adventure Comedy Sci-Fi,guardians of the galaxy vol. 2,Chris Pratt Zoe Saldana Dave Bautista James Gu...
4,Sean McNamara,Pierce Brosnan,William Hurt,Benjamin Walker,Fantasy Action Adventure,the king's daughter,Pierce Brosnan William Hurt Benjamin Walker Se...

In [38]:
df.to_csv("../Data/processed/movie_metadata_2017.csv", index=False)

In [39]:
old = pd.read_csv("../Data/processed/processed_movie_metadata.csv")
old.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...

In [40]:
old['comb'] = old['actor_1_name'] + ' ' + old['actor_2_name'] + ' ' + old['actor_3_name'] + ' ' + old['director_name'] + ' ' + old['genres']

In [41]:
old.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...

In [45]:
new = pd.concat([old, df])
new.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...

In [47]:
new.shape

(5501, 7)

In [48]:
new.duplicated().sum()

np.int64(123)

In [49]:
new.drop_duplicates(subset = "movie_title", keep="last",inplace=True)
new

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
524,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
525,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
526,Hannaleena Hauru,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mäntyvaara,Inka Haapamäki Rosa Honkonen Tiitus Rantala Ha...
527,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
529,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [50]:
new.to_csv("../Data/processed/processed_combined_movie_metadata.csv", index=False)